### PR TITLE
Implements `useMethod`

### LINKED ISSUE #3: Add useMethod for meteor method calls
I've be using the following in my apps and it's working well:

```js
import { useState } from 'react'
import { Meteor } from 'meteor/meteor'

export function useMethod(methodName, { transform } = {}) {
  const [isLoading, setIsLoading] = useState(false)
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  const call = (...args) => {
    setIsLoading(true)
    return new Promise((resolve, reject) => {
      Meteor.call(methodName, ...args, (err, result) => {
        if (err) {
          setError(err)
          reject(err)
        } else {
          setData(transform ? transform(result) : result)
          resolve(result)
        }
        setIsLoading(false)
      })
    })
  }

  return { isLoading, data, error, call }
}
```

Example: https://codesandbox.io/s/kj9zqqyrr

I can create a PR if you think this would be useful.

### PR DESCRIPTION
**Pull request by maxfi**
Issue #3

### CODE REVIEW

**Comment by maxfi** [comment]
@andruschka

**Comment by JoschuaSchneider** [comment]
This is a very nice addition!

What do you think about resetting the `error` state when a second `call()` succeeds?
That would also make it necessary to utilize `useReducer` to prevent the `setData` and `setError` calls to update the component twice.

The idea I have is based on something like this:
```javascript
return (
  <div>
    {error && (<p>Some error with the provided parameters</p>)}
    {data && <Display data={data} />}
    <button onClick={() => retryCall()}>Retry</button>
  </div>
)
```

This would keep showing the error state, even if a subsequent call succeeds.

**Comment by JoschuaSchneider** [comment]
This would be an example implementation based on your PR:

```javascript
  const [{ isLoading, error, data }, dispatch] = useReducer(
    (state, action) => {
      switch (action.type) {
        case 'loading':
          return { ...state, isLoading: true }
        case 'success':
          return {
            ...state,
            isLoading: false,
            error: null,
            data: action.payload
          }
        case 'failure':
          return {
            ...state,
            isLoading: false,
            error: action.payload,
            data: null
          }
        default:
          return state
      }
    },
    {
      isLoading: false,
      data: null,
      error: null
    }
  )

  const call = (...args) => {
    dispatch({ type: 'loading' })
    return new Promise((resolve, reject) => {
      Meteor.call(methodName, ...args, (err, result) => {
        if (err) {
          dispatch({ type: 'failure', payload: err })
          reject(err)
        } else {
          dispatch({
            type: 'success',
            payload: transform ? transform(result) : result
          })
          resolve(result)
        }
      })
    })
  }
```

The **benefit** of this approach would be that in the event of a successful call, the data is set and the error becomes null again. And in case of an error, data gets cleared and the error is set.
In both cases, isLoading gets set in the same call.

This saves **two rerenders** regardless of the additional error reset. Because setState calls don't get batched yet.

So calling setLoading -> setData/setError -> setLoading results in an additional re-render (3 in total).
The approach that I suggest here, causes only two re-renders, regardless of the outcome of the call.

I hope that I didn't miss the point here :smile:

**Comment by maxfi** [comment]
Nice one @JoschuaSchneider! I've updated the PR.

@andruschka LGTM 🙏

**Comment by andruschka** [comment]
thank you guys. nice work

**Pull request merged**
